addSbtPlugin("org.scoverage"  % "sbt-scoverage" % "1.7.0")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"  % "2.4.3")
addSbtPlugin("com.dwijnand"   % "sbt-dynver"    % "4.1.1")
addSbtPlugin("com.jsuereth"   % "sbt-pgp"       % "2.0.2")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype"  % "3.9.7")
addSbtPlugin("com.codecommit" % "sbt-github-actions" % "0.13.0")
