addSbtPlugin("org.scoverage"  % "sbt-scoverage" % "1.6.1")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"  % "2.3.4")
addSbtPlugin("com.dwijnand"   % "sbt-dynver"    % "4.1.1")
addSbtPlugin("com.jsuereth"   % "sbt-pgp"       % "2.0.2")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype"  % "3.9.6")
